### ISSUE TITLE
Spatial data structure not working well

### ISSUE THREAD

**Issue by darrylvo** [codyrhoads/ATTRACT#6]
Not only does the KD-tree not seem to be working for ray casting, it is inefficient because the nature of our block level design. fix it up or use a new one???? who knows

**Comment by codyrhoads** [comment]
I'll work on implementing a bounding volume hierarchy instead of a kd-tree this weekend.

**Comment by codyrhoads** [comment]
I've implemented BVH. Seems to function correctly. Though I don't know if the time saved from pruning objects outweighs the time needed to do the necessary work for BVH. It'll become more apparent when we add more objects to the scene.
